"""Emit every manuscript number as a LaTeX macro, straight from results.json."""
import json, pathlib
ROOT = pathlib.Path(__file__).resolve().parents[1]
R = json.loads((ROOT / "results_full" / "results.json").read_text())
L = []
_W = {"3": "Three", "4": "Four", "5": "Five", "6": "Six", "7": "Seven"}
def mac(name, val):
    for d, w in _W.items():
        name = name.replace(d, w)
    L.append(r"\newcommand{\%s}{%s}" % (name, val))
def com(x): return f"{int(x):,}".replace(",", r"{,}")
def sci(x):
    s = "%.2e" % x; m, e = s.split("e")
    return r"%s\times10^{%d}" % (m, int(e))

v = R["verification"]
mac("VerGraphs", com(v["n_graphs"])); mac("VerValues", com(v["n_values"]))
mac("VerMaxErr", sci(v["max_abs_error"]))
for i, k in enumerate(("Pet", "Cyc", "Hea")):
    c = R["collision_pairs"][i]
    mac(k + "Gap", sci(c["max_surface_gap_statevector"]))
    mac(k + "Na", str(c["n_a"])); mac(k + "Nb", str(c["n_b"]))
    mac(k + "Ga", str(c["girth_a"])); mac(k + "Gb", str(c["girth_b"]))
t = R["transfer"]
mac("XPairs", com(t["n_pairs"])); mac("XViol", com(t["bound_violations_sup"] + t["bound_violations_transfer"]))
mac("XSpear", "%.2f" % t["spearman_gap_tv"]); mac("XMedRatio", "%.2f" % t["median_ratio_gap_over_tv"])
mac("CorpusSize", com(t["corpus_size"])); mac("AnglePoints", com(t["angle_points"]))
lk = R["leakage"]
mac("LeakPairs", com(lk["pairs"])); mac("LeakIdentical", com(lk["statistic_identical_pairs"]))
mac("LeakIso", com(lk["isomorphic_pairs"])); mac("LeakMissed", com(lk["collisions_missed_by_isomorphism"]))
for d in ("3", "4", "5"):
    r = R["regular_benchmark"][d]
    mac(f"RegG{d}", com(r["graphs"])); mac(f"RegC{d}", com(r["statistic_classes"]))
    mac(f"RegShare{d}", "%.1f" % (100 * r["shared_fraction"]))
for n in ("5", "6", "7"):
    c = R["small_graph_census"][n]
    mac(f"CenG{n}", com(c["connected_graphs"])); mac(f"CenC{n}", com(c["statistic_classes"]))
    mac(f"CenShare{n}", "%.1f" % (100 * c["shared_fraction"]))
cl = R["corpus_landscapes"]
mac("CorpusLandscapes", com(cl["distinct_landscapes"]))
nl = R["naive_split_leakage"]
mac("NaiveLeak", com(nl["test_graphs_with_identical_landscape_in_training"]))
mac("NaiveLeakPct", "%.0f" % (100 * nl["test_graphs_with_identical_landscape_in_training"] / nl["total_test_graphs"]))
for split, tag in (("regret_naive", "Naive"), ("regret_grouped", "Group")):
    for meth in ("mean", "ridge", "spectral"):
        mac(tag + meth.capitalize(), "%.5f" % R[split][meth]["1"])
mac("SpecInflation", "%.0f" % (R["regret_grouped"]["spectral"]["1"] / R["regret_naive"]["spectral"]["1"]))
rs = R["runtime_small"][-1]
mac("RunN", str(rs["n"])); mac("RunFormula", "%.0f" % (1e6 * rs["formula_s"]))
mac("RunState", "%.1f" % rs["statevector_s"])
mac("RunSpeedup", com(round(rs["statevector_s"] / rs["formula_s"], -2)))
bg = max(R["runtime_gset"], key=lambda d: d["m"])
mac("GsetName", bg["name"]); mac("GsetN", com(bg["n"])); mac("GsetM", com(bg["m"]))
mac("GsetT", com(bg["unique_triples"])); mac("GsetSurf", "%.0f" % (1000 * bg["surface_s"]))
mac("GsetPre", "%.2f" % bg["preprocess_s"])
sc = max(R["scaling"], key=lambda d: d["m"])
mac("ScalM", com(sc["m"])); mac("ScalT", com(sc["unique_triples"]))
mac("ScalPre", "%.1f" % sc["preprocess_s"]); mac("ScalSurf", "%.1f" % sc["surface_s"])
mac("Compress", "%.1f" % R["compression"]["median_ratio_m_over_T"])
mac("NGset", str(len(R["gset_unweighted"])))
out = ROOT.parent / "numbers.tex"
out.write_text("% generated by code/scripts/numbers.py -- do not edit\n" + "\n".join(L) + "\n")
print("wrote", out, len(L), "macros")
